/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import code.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    
    Connection con = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;
    PreparedStatement pst4 = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    
    public ChangePassword() throws ClassNotFoundException {
        initComponents();
        con = DBConnect.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailBox = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        cancelBuutton = new javax.swing.JButton();
        passwordBox = new javax.swing.JPasswordField();
        conformBox = new javax.swing.JPasswordField();
        passwordShowBox = new javax.swing.JCheckBox();
        conformShowBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");

        jLabel1.setText("email");

        jLabel2.setText("new password");

        jLabel3.setText("conform password");

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        cancelBuutton.setText("Cancel");
        cancelBuutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBuuttonActionPerformed(evt);
            }
        });

        conformBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conformBoxActionPerformed(evt);
            }
        });

        passwordShowBox.setText("Show");
        passwordShowBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordShowBoxActionPerformed(evt);
            }
        });

        conformShowBox.setText("Show");
        conformShowBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conformShowBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(changeButton)
                        .addGap(74, 74, 74)
                        .addComponent(cancelBuutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailBox)
                            .addComponent(passwordBox)
                            .addComponent(conformBox, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordShowBox)
                            .addComponent(conformShowBox))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordShowBox))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(conformBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conformShowBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeButton)
                    .addComponent(cancelBuutton))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBuuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBuuttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBuuttonActionPerformed

    private void conformBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conformBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conformBoxActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        String email;
        String newPassword;
        String conform;
        Boolean cus = false;
        Boolean sel = false;
        String query1 = "SELECT customerID FROM customers WHERE email = ?";
        String query2 = "SELECT sellerID FROM sellers WHERE email = ?";
        String query3 = "UPDATE customers SET password = ? WHERE email = ?";
        String query4 = "UPDATE sellers SET password = ? WHERE email = ?";
        
        email = emailBox.getText();
        newPassword = new String(passwordBox.getPassword());
        conform = new String(conformBox.getPassword());
        
        try {
            pst1 = con.prepareStatement(query1);
            pst1.setString(1, email);
            rs1 = pst1.executeQuery();
            
            pst2 = con.prepareStatement(query2);
            pst2.setString(1, email);
            rs2 = pst2.executeQuery();
            cus = rs1.next();
            sel = rs2.next();
            
        } catch (SQLException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(newPassword.equals(conform)){
            if(cus && sel){
                try {
                    pst3 = con.prepareStatement(query3);
                    pst3.setString(1, newPassword);
                    pst3.setString(2, email);
                    pst3.execute();
                    
                    pst4 = con.prepareStatement(query4);
                    pst4.setString(1, newPassword);
                    pst4.setString(2, email);
                    pst4.execute();
                    
                    JOptionPane.showMessageDialog(null, "changed Succesfully");
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(cus){
                try {
                    pst3 = con.prepareStatement(query3);
                    pst3.setString(1, newPassword);
                    pst3.setString(2, email);
                    pst3.execute();
                    
                    JOptionPane.showMessageDialog(null, "changed Succesfully");
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(sel){
                try {
                    pst4 = con.prepareStatement(query4);
                    pst4.setString(1, newPassword);
                    pst4.setString(2, email);
                    pst4.execute();
                    
                    JOptionPane.showMessageDialog(null, "changed Succesfully");
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "there is not a acount registerd with this emaill");
                this.dispose();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "your new password and conform password is not equal");
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void passwordShowBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordShowBoxActionPerformed
        if(passwordShowBox.isSelected()){
            passwordBox.setEchoChar((char)0);
        }
        else{
            passwordBox.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordShowBoxActionPerformed

    private void conformShowBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conformShowBoxActionPerformed
        if(conformShowBox.isSelected()){
            conformBox.setEchoChar((char)0);
        }
        else{
            conformBox.setEchoChar('*');
        } 
    }//GEN-LAST:event_conformShowBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChangePassword().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBuutton;
    private javax.swing.JButton changeButton;
    private javax.swing.JPasswordField conformBox;
    private javax.swing.JCheckBox conformShowBox;
    private javax.swing.JTextField emailBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JCheckBox passwordShowBox;
    // End of variables declaration//GEN-END:variables
}
