/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import code.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class selRegister extends javax.swing.JFrame {

    /**
     * Creates new form selRegister
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;
    ResultSet rs1 = null;
    
    public selRegister() throws ClassNotFoundException {
        initComponents();
        
        con = DBConnect.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameBox = new javax.swing.JTextField();
        emailBox = new javax.swing.JTextField();
        passwordBox = new javax.swing.JPasswordField();
        mobileNumberBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        breakfastBox = new javax.swing.JCheckBox();
        backeryBox = new javax.swing.JCheckBox();
        lunchBox = new javax.swing.JCheckBox();
        registerButton = new javax.swing.JButton();
        dinnerBox = new javax.swing.JCheckBox();
        bigOrderBox = new javax.swing.JCheckBox();
        sweetBox = new javax.swing.JCheckBox();
        fruitBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        jLabel1.setText("User name");

        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Password");

        jLabel4.setText("Mobile number");

        userNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Food item catagory");

        breakfastBox.setText("Breakfast");
        breakfastBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfastBoxActionPerformed(evt);
            }
        });

        backeryBox.setText("Backery Items");

        lunchBox.setText("Lunch");
        lunchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunchBoxActionPerformed(evt);
            }
        });

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        dinnerBox.setText("Dinner");

        bigOrderBox.setText("Big orders");
        bigOrderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigOrderBoxActionPerformed(evt);
            }
        });

        sweetBox.setText("Sweets");

        fruitBox.setText("Fruits");
        fruitBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bigOrderBox)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(backeryBox)
                                .addComponent(sweetBox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(breakfastBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lunchBox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dinnerBox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fruitBox, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(registerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordBox, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(userNameBox)
                            .addComponent(emailBox)
                            .addComponent(mobileNumberBox))
                        .addGap(30, 30, 30)
                        .addComponent(showPasswordCheckBox)))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPasswordCheckBox))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breakfastBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lunchBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dinnerBox)
                .addGap(5, 5, 5)
                .addComponent(sweetBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fruitBox)
                .addGap(5, 5, 5)
                .addComponent(backeryBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bigOrderBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if(showPasswordCheckBox.isSelected()){
            passwordBox.setEchoChar((char)0);
        }
        else{
            passwordBox.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    private void userNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameBoxActionPerformed

    private void breakfastBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfastBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breakfastBoxActionPerformed

    private void lunchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunchBoxActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String userName;
        String email;
        String password;
        String mobileNumber;
        String t = "true";
        userName = userNameBox.getText();
        email = emailBox.getText();
        password = new String(passwordBox.getPassword());
        mobileNumber = mobileNumberBox.getText();
        String quary;

        try {
            if(checkEmail(email)){
                JOptionPane.showMessageDialog(null , "You have registered with this email now please login");
                log lg = new log();
                lg.setVisible(true);
                this.dispose();
            }
            else{
                String quary1 = "INSERT INTO sellers (username , email , password , mobilenumber) VALUES ('"+ userName +"' , '"+ email +"' , '"+ password +"' , '"+ mobileNumber +"')";
                pst = con.prepareStatement(quary1);
                pst.execute();

                if(breakfastBox.isSelected()){
                    quary = "UPDATE sellers SET breakfast = ? WHERE email = ?";
                    pst3 = con.prepareStatement(quary);
                    pst3.setString(1, t);
                    pst3.setString(2, email);
                    pst3.execute();
                }
                if(lunchBox.isSelected()){
                    quary = "UPDATE sellers SET lunch = ? WHERE email = ?";
                    pst3 = con.prepareStatement(quary);
                    pst3.setString(1, t);
                    pst3.setString(2, email);
                    pst3.execute();
                }
                if(dinnerBox.isSelected()){
                    quary = "UPDATE sellers SET dinner = ? WHERE email = ?";
                    pst3 = con.prepareStatement(quary);
                    pst3.setString(1, t);
                    pst3.setString(2, email);
                    pst3.execute();
                }
                if(sweetBox.isSelected()){
                    quary = "UPDATE sellers SET sweet = ? WHERE email = ?";
                    pst3 = con.prepareStatement(quary);
                    pst3.setString(1, t);
                    pst3.setString(2, email);
                    pst3.execute();
                }
                if(fruitBox.isSelected()){
                    quary = "UPDATE sellers SET fruit = ? WHERE email = ?";
                    pst3 = con.prepareStatement(quary);
                    pst3.setString(1, t);
                    pst3.setString(2, email);
                    pst3.execute();
                }
                if(backeryBox.isSelected()){
                    quary = "UPDATE sellers SET backery = ? WHERE email = ?";
                    pst3 = con.prepareStatement(quary);
                    pst3.setString(1, t);
                    pst3.setString(2, email);
                    pst3.execute();
                }
                if(bigOrderBox.isSelected()){
                    quary = "UPDATE sellers SET bigorder = ? WHERE email = ?";
                    pst3 = con.prepareStatement(quary);
                    pst3.setString(1, t);
                    pst3.setString(2, email);
                    pst3.execute();
                }

                this.dispose();
                JOptionPane.showMessageDialog(null, "Register Succesfully");

                log lg = new log();
                lg.setVisible(true);
            }
        }
        catch (SQLException e) {
            System.out.println(e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cusSelRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void bigOrderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigOrderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigOrderBoxActionPerformed

    private void fruitBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fruitBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private Boolean checkEmail(String x) throws SQLException{
        String q1 = "SELECT email FROM sellers WHERE email = ?";
        
        pst2 = con.prepareStatement(q1);
        pst2.setString(1, x);
        rs1 = pst2.executeQuery();
        
        return rs1.next();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new selRegister().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(selRegister.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox backeryBox;
    private javax.swing.JCheckBox bigOrderBox;
    private javax.swing.JCheckBox breakfastBox;
    private javax.swing.JCheckBox dinnerBox;
    private javax.swing.JTextField emailBox;
    private javax.swing.JCheckBox fruitBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox lunchBox;
    private javax.swing.JTextField mobileNumberBox;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JButton registerButton;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JCheckBox sweetBox;
    private javax.swing.JTextField userNameBox;
    // End of variables declaration//GEN-END:variables
}
